import type { User, Venue, Booking } from '../types';
import { 
  getUsers, 
  saveUsers, 
  getVenues, 
  saveVenues, 
  getBookings, 
  saveBookings, 
  getVenueAvailability, 
  saveVenueAvailability 
} from './localStorage';
import { mockVenues } from './mockData';

export const initializeMockData = () => {
    // Initialize venue availability if not present
    const existingAvailability = getVenueAvailability();
    if (existingAvailability.length === 0) {
      const venues = getVenues();
      // Use a range of dates (today and next 364 days)
      const today = new Date();
      const dateStrings = Array.from({ length: 365 }, (_, i) => {
        const d = new Date(today);
        d.setDate(today.getDate() + i);
        return d.toISOString().slice(0, 10);
      });
      const timeSlots = [
        '9:00 AM - 12:00 PM',
        '12:00 PM - 3:00 PM',
        '3:00 PM - 6:00 PM',
        '6:00 PM - 9:00 PM',
        '9:00 PM - 12:00 AM',
      ];
      const availability = [];
      for (const venue of venues) {
        for (const date of dateStrings) {
          availability.push({
            id: `${venue.id}-${date}`,
            venueId: venue.id,
            date,
            timeSlots: [...timeSlots],
          });
        }
      }
      saveVenueAvailability(availability);
    }
  // Only initialize if there's no data yet
  const existingVenues = getVenues();
  const existingBookings = getBookings();
  
  if (existingVenues.length === 0) {
    // If no venues in localStorage, initialize from mockVenues
    saveVenues(mockVenues.map(v => ({ ...v, providerId: 'provider-1', isApproved: true, availability: true, createdAt: new Date().toISOString() })));
  }
  if (existingBookings.length > 0) {
    return; // Bookings already exist, skip
  }

  // Create sample users
  const sampleUsers: User[] = [
    {
      id: 'provider-1',
      fullName: 'Sarah Johnson',
      email: 'sarah@venues.com',
      password: 'provider123',
      role: 'provider',
      createdAt: '2025-01-15T10:00:00Z',
      isBlocked: false,
    },
    {
      id: 'provider-2',
      fullName: 'Michael Chen',
      email: 'michael@venues.com',
      password: 'provider123',
      role: 'provider',
      createdAt: '2025-01-20T10:00:00Z',
      isBlocked: false,
    },
    {
      id: 'customer-1',
      fullName: 'Emily Davis',
      email: 'emily@customer.com',
      password: 'customer123',
      role: 'customer',
      createdAt: '2025-02-01T10:00:00Z',
      isBlocked: false,
    },
    {
      id: 'customer-2',
      fullName: 'David Martinez',
      email: 'david@customer.com',
      password: 'customer123',
      role: 'customer',
      createdAt: '2025-02-05T10:00:00Z',
      isBlocked: false,
    },
  ];

  // Merge with existing users (keeping admin)
  const currentUsers = getUsers();
  const mergedUsers = [...currentUsers, ...sampleUsers.filter(su => !currentUsers.find(u => u.id === su.id))];
  saveUsers(mergedUsers);

  // Create sample venues
  const sampleVenues: Venue[] = [
    {
      id: 'venue-1',
      providerId: 'provider-1',
      name: 'The Leela Palace',
      location: 'New Delhi',
      price: 80000,
      description: 'Luxury venue for weddings and corporate events.',
      image: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3',
      availability: true,
      isApproved: true,
      createdAt: '2025-01-16T10:00:00Z',
      capacity: 300,
      amenities: ['Parking', 'WiFi', 'Catering'],
    },
    {
      id: 'venue-2',
      providerId: 'provider-1',
      name: 'Taj Lands End',
      location: 'Mumbai',
      price: 120000,
      description: 'Premium sea-facing banquet venue.',
      image: 'https://images.unsplash.com/photo-1505236858219-8359eb29e329',
      availability: true,
      isApproved: true,
      createdAt: '2025-01-17T10:00:00Z',
      capacity: 500,
      amenities: ['Parking', 'Valet', 'Catering'],
    },
    {
      id: 'venue-3',
      providerId: 'provider-2',
      name: 'ITC Gardenia',
      location: 'Bengaluru',
      price: 60000,
      description: 'Elegant garden venue for events.',
      image: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3',
      availability: true,
      isApproved: true,
      createdAt: '2025-01-18T10:00:00Z',
      capacity: 250,
      amenities: ['Garden', 'Outdoor', 'WiFi'],
    },
    {
      id: 'venue-4',
      providerId: 'provider-2',
      name: 'Novotel Convention Center',
      location: 'Hyderabad',
      price: 70000,
      description: 'Modern convention venue.',
      image: 'https://images.unsplash.com/photo-1503428593586-e225b39bddfe',
      availability: true,
      isApproved: true,
      createdAt: '2025-01-19T10:00:00Z',
      capacity: 600,
      amenities: ['WiFi', 'Parking', 'AC'],
    },
    {
      id: 'venue-5',
      providerId: 'provider-1',
      name: 'ITC Grand Chola',
      location: 'Chennai',
      price: 90000,
      description: 'Grand ballroom for large events.',
      image: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622',
      availability: true,
      isApproved: true,
      createdAt: '2025-01-20T10:00:00Z',
      capacity: 400,
      amenities: ['WiFi', 'Catering', 'Parking'],
    },
    {
      id: 'venue-6',
      providerId: 'provider-2',
      name: 'JW Marriott',
      location: 'Kolkata',
      price: 85000,
      description: 'Luxury indoor banquet hall.',
      image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30',
      availability: true,
      isApproved: true,
      createdAt: '2025-01-21T10:00:00Z',
      capacity: 350,
      amenities: ['WiFi', 'Valet', 'Parking'],
    },
    {
      id: 'venue-7',
      providerId: 'provider-1',
      name: 'Courtyard by Marriott',
      location: 'Ahmedabad',
      price: 50000,
      description: 'Perfect venue for mid-size events.',
      image: 'https://images.unsplash.com/photo-1528605248644-14dd04022da1',
      availability: true,
      isApproved: true,
      createdAt: '2025-01-22T10:00:00Z',
      capacity: 200,
      amenities: ['WiFi', 'Parking', 'Catering'],
    },
    {
      id: 'venue-8',
      providerId: 'provider-2',
      name: 'Hyatt Pune',
      location: 'Pune',
      price: 60000,
      description: 'Modern banquet for weddings.',
      image: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205',
      availability: true,
      isApproved: true,
      createdAt: '2025-01-23T10:00:00Z',
      capacity: 300,
      amenities: ['Parking', 'WiFi', 'AC'],
    },
    {
      id: 'venue-9',
      providerId: 'provider-1',
      name: 'Radisson Blu',
      location: 'Jaipur',
      price: 55000,
      description: 'Elegant venue for celebrations.',
      image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836',
      availability: true,
      isApproved: true,
      createdAt: '2025-01-24T10:00:00Z',
      capacity: 300,
      amenities: ['Outdoor', 'Parking', 'Catering'],
    },
    {
      id: 'venue-10',
      providerId: 'provider-2',
      name: 'Marriott Hotel',
      location: 'Surat',
      price: 45000,
      description: 'Spacious indoor venue.',
      image: 'https://images.unsplash.com/photo-1505691938895-1758d7feb511',
      availability: true,
      isApproved: true,
      createdAt: '2025-01-25T10:00:00Z',
      capacity: 250,
      amenities: ['WiFi', 'Parking', 'AC'],
    },
    {
      id: 'venue-11',
      providerId: 'provider-1',
      name: 'Clarks Avadh',
      location: 'Lucknow',
      price: 50000,
      description: 'Classic banquet hall for weddings.',
      image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb',
      availability: true,
      isApproved: true,
      createdAt: '2025-01-26T10:00:00Z',
      capacity: 300,
      amenities: ['Parking', 'Catering', 'WiFi'],
    },
    {
      id: 'venue-12',
      providerId: 'provider-2',
      name: 'The Landmark Hotel',
      location: 'Kanpur',
      price: 40000,
      description: 'Popular venue for events.',
      image: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae',
      availability: true,
      isApproved: true,
      createdAt: '2025-01-27T10:00:00Z',
      capacity: 200,
      amenities: ['WiFi', 'Parking'],
    },
    {
      id: 'venue-13',
      providerId: 'provider-1',
      name: 'Radisson Blu',
      location: 'Nagpur',
      price: 45000,
      description: 'Modern banquet facility.',
      image: 'https://images.unsplash.com/photo-1478145046317-39f10e56b5e9',
      availability: true,
      isApproved: true,
      createdAt: '2025-01-28T10:00:00Z',
      capacity: 300,
      amenities: ['Parking', 'WiFi'],
    },
    {
      id: 'venue-14',
      providerId: 'provider-2',
      name: 'Sayaji Hotel',
      location: 'Indore',
      price: 55000,
      description: 'Premium venue for functions.',
      image: 'https://images.unsplash.com/photo-1492724441997-5dc865305da7',
      availability: true,
      isApproved: true,
      createdAt: '2025-01-29T10:00:00Z',
      capacity: 350,
      amenities: ['WiFi', 'Parking'],
    },
    {
      id: 'venue-15',
      providerId: 'provider-1',
      name: 'Jehan Numa Palace',
      location: 'Bhopal',
      price: 50000,
      description: 'Royal heritage venue.',
      image: 'https://images.unsplash.com/photo-1496412705862-e0088f16f791',
      availability: true,
      isApproved: true,
      createdAt: '2025-01-30T10:00:00Z',
      capacity: 200,
      amenities: ['Outdoor', 'Catering'],
    },
    {
      id: 'venue-16',
      providerId: 'provider-2',
      name: 'Hotel Maurya',
      location: 'Patna',
      price: 45000,
      description: 'Well-known banquet venue.',
      image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858',
      availability: true,
      isApproved: true,
      createdAt: '2025-02-01T10:00:00Z',
      capacity: 250,
      amenities: ['Parking', 'WiFi'],
    },
    {
      id: 'venue-17',
      providerId: 'provider-1',
      name: 'Capitol Hill',
      location: 'Ranchi',
      price: 35000,
      description: 'Comfortable venue for events.',
      image: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187',
      availability: true,
      isApproved: true,
      createdAt: '2025-02-02T10:00:00Z',
      capacity: 200,
      amenities: ['WiFi', 'Parking'],
    },
    {
      id: 'venue-18',
      providerId: 'provider-2',
      name: 'Hotel Babylon',
      location: 'Raipur',
      price: 40000,
      description: 'Modern banquet space.',
      image: 'https://images.unsplash.com/photo-1499951360447-b19be8fe80f5',
      availability: true,
      isApproved: true,
      createdAt: '2025-02-03T10:00:00Z',
      capacity: 250,
      amenities: ['WiFi', 'Parking'],
    },
    {
      id: 'venue-19',
      providerId: 'provider-1',
      name: 'Taj Chandigarh',
      location: 'Chandigarh',
      price: 70000,
      description: 'Luxury venue with premium services.',
      image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85',
      availability: true,
      isApproved: true,
      createdAt: '2025-02-04T10:00:00Z',
      capacity: 300,
      amenities: ['Valet', 'WiFi'],
    },
    {
      id: 'venue-20',
      providerId: 'provider-2',
      name: 'Hyatt Regency',
      location: 'Amritsar',
      price: 60000,
      description: 'Stylish event venue.',
      image: 'https://images.unsplash.com/photo-1505691723518-36a5ac3b2e1b',
      availability: true,
      isApproved: true,
      createdAt: '2025-02-05T10:00:00Z',
      capacity: 250,
      amenities: ['WiFi', 'Parking'],
    },
    {
      id: 'venue-21',
      providerId: 'provider-1',
      name: 'Radisson Blu',
      location: 'Ludhiana',
      price: 50000,
      description: 'Elegant banquet hall.',
      image: 'https://images.unsplash.com/photo-1505691938895-1758d7feb511',
      availability: true,
      isApproved: true,
      createdAt: '2025-02-06T10:00:00Z',
      capacity: 250,
      amenities: ['Parking', 'WiFi'],
    },
    {
      id: 'venue-22',
      providerId: 'provider-2',
      name: 'Hotel Clarks Shiraz',
      location: 'Agra',
      price: 55000,
      description: 'Venue near Taj Mahal.',
      image: 'https://images.unsplash.com/photo-1494526585095-c41746248156',
      availability: true,
      isApproved: true,
      createdAt: '2025-02-07T10:00:00Z',
      capacity: 300,
      amenities: ['Catering', 'Parking'],
    },
    {
      id: 'venue-23',
      providerId: 'provider-1',
      name: 'Taj Ganges',
      location: 'Varanasi',
      price: 50000,
      description: 'Peaceful venue with heritage feel.',
      image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85',
      availability: true,
      isApproved: true,
      createdAt: '2025-02-08T10:00:00Z',
      capacity: 200,
      amenities: ['WiFi', 'Parking'],
    },
    {
      id: 'venue-24',
      providerId: 'provider-2',
      name: 'Hotel Harmony Inn',
      location: 'Meerut',
      price: 30000,
      description: 'Affordable event venue.',
      image: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae',
      availability: true,
      isApproved: true,
      createdAt: '2025-02-09T10:00:00Z',
      capacity: 150,
      amenities: ['Parking'],
    },
    {
      id: 'venue-25',
      providerId: 'provider-1',
      name: 'Le Meridien',
      location: 'Coimbatore',
      price: 50000,
      description: 'Modern banquet hall.',
      image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb',
      availability: true,
      isApproved: true,
      createdAt: '2025-02-10T10:00:00Z',
      capacity: 250,
      amenities: ['WiFi', 'Parking'],
    },
    {
      id: 'venue-26',
      providerId: 'provider-2',
      name: 'Heritage Madurai',
      location: 'Madurai',
      price: 45000,
      description: 'Luxury outdoor venue.',
      image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858',
      availability: true,
      isApproved: true,
      createdAt: '2025-02-11T10:00:00Z',
      capacity: 200,
      amenities: ['Garden', 'Parking'],
    },
    {
      id: 'venue-27',
      providerId: 'provider-1',
      name: 'Novotel',
      location: 'Visakhapatnam',
      price: 60000,
      description: 'Sea-facing banquet venue.',
      image: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187',
      availability: true,
      isApproved: true,
      createdAt: '2025-02-12T10:00:00Z',
      capacity: 300,
      amenities: ['WiFi', 'Parking'],
    },
    {
      id: 'venue-28',
      providerId: 'provider-2',
      name: 'The Gateway Hotel',
      location: 'Vijayawada',
      price: 45000,
      description: 'Comfortable venue for events.',
      image: 'https://images.unsplash.com/photo-1499951360447-b19be8fe80f5',
      availability: true,
      isApproved: true,
      createdAt: '2025-02-13T10:00:00Z',
      capacity: 250,
      amenities: ['WiFi', 'Parking'],
    },
    {
      id: 'venue-29',
      providerId: 'provider-1',
      name: 'Hyatt Regency',
      location: 'Thiruvananthapuram',
      price: 60000,
      description: 'Premium indoor venue.',
      image: 'https://images.unsplash.com/photo-1505691723518-36a5ac3b2e1b',
      availability: true,
      isApproved: true,
      createdAt: '2025-02-14T10:00:00Z',
      capacity: 250,
      amenities: ['WiFi', 'Parking'],
    },
    {
      id: 'venue-30',
      providerId: 'provider-2',
      name: 'Grand Hyatt',
      location: 'Kochi',
      price: 90000,
      description: 'Luxury waterfront venue.',
      image: 'https://images.unsplash.com/photo-1494526585095-c41746248156',
      availability: true,
      isApproved: true,
      createdAt: '2025-02-15T10:00:00Z',
      capacity: 400,
      amenities: ['Parking', 'WiFi'],
    },
    {
      id: 'venue-31',
      providerId: 'provider-1',
      name: 'Radisson Blu',
      location: 'Mysuru',
      price: 50000,
      description: 'Elegant venue for events.',
      image: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622',
      availability: true,
      isApproved: true,
      createdAt: '2025-02-16T10:00:00Z',
      capacity: 200,
      amenities: ['WiFi', 'Parking'],
    },
    {
      id: 'venue-32',
      providerId: 'provider-2',
      name: 'Goldfinch Hotel',
      location: 'Mangaluru',
      price: 40000,
      description: 'Modern banquet venue.',
      image: 'https://images.unsplash.com/photo-1505236858219-8359eb29e329',
      availability: true,
      isApproved: true,
      createdAt: '2025-02-17T10:00:00Z',
      capacity: 200,
      amenities: ['Parking', 'WiFi'],
    },
    {
      id: 'venue-33',
      providerId: 'provider-1',
      name: 'Umaid Bhawan Palace',
      location: 'Jodhpur',
      price: 200000,
      description: 'Royal palace wedding venue.',
      image: 'https://images.unsplash.com/photo-1503428593586-e225b39bddfe',
      availability: true,
      isApproved: true,
      createdAt: '2025-02-18T10:00:00Z',
      capacity: 300,
      amenities: ['Luxury Stay', 'Catering'],
    },
    {
      id: 'venue-34',
      providerId: 'provider-2',
      name: 'The Oberoi Udaivilas',
      location: 'Udaipur',
      price: 180000,
      description: 'Luxury lake-side wedding venue.',
      image: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3',
      availability: true,
      isApproved: true,
      createdAt: '2025-02-19T10:00:00Z',
      capacity: 200,
      amenities: ['Lake View', 'Luxury'],
    },
    {
      id: 'venue-35',
      providerId: 'provider-1',
      name: 'Hyatt Regency',
      location: 'Dehradun',
      price: 50000,
      description: 'Peaceful hill venue.',
      image: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae',
      availability: true,
      isApproved: true,
      createdAt: '2025-02-20T10:00:00Z',
      capacity: 200,
      amenities: ['Parking', 'WiFi'],
    },
    {
      id: 'venue-36',
      providerId: 'provider-2',
      name: 'Crystal Banquet Hall',
      location: 'Gurgaon',
      price: 65000,
      description: 'Elegant hall with modern lighting and stage facilities.',
      image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750',
      availability: true,
      isApproved: true,
      createdAt: '2025-02-21T10:00:00Z',
      capacity: 280,
      amenities: ['WiFi', 'Catering', 'Parking'],
    },
    {
      id: 'venue-37',
      providerId: 'provider-1',
      name: 'Island View Lounge',
      location: 'Goa',
      price: 95000,
      description: 'Seaside lounge venue with panoramic views and premium service.',
      image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85',
      availability: true,
      isApproved: true,
      createdAt: '2025-02-22T10:00:00Z',
      capacity: 220,
      amenities: ['Outdoor', 'Bar', 'Parking'],
    },
    {
      id: 'venue-38',
      providerId: 'provider-2',
      name: 'Emerald Conference Hall',
      location: 'Chandigarh',
      price: 52000,
      description: 'Business-friendly conference hall with full AV support.',
      image: 'https://images.unsplash.com/photo-1494526585095-c41746248156',
      availability: true,
      isApproved: true,
      createdAt: '2025-02-23T10:00:00Z',
      capacity: 260,
      amenities: ['WiFi', 'Projector', 'Parking'],
    },
    {
      id: 'venue-39',
      providerId: 'provider-1',
      name: 'Lotus Garden Estate',
      location: 'Noida',
      price: 78000,
      description: 'Lush garden estate perfect for large outdoor weddings.',
      image: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205',
      availability: true,
      isApproved: true,
      createdAt: '2025-02-24T10:00:00Z',
      capacity: 420,
      amenities: ['Outdoor', 'Catering', 'Parking'],
    },
    {
      id: 'venue-40',
      providerId: 'provider-2',
      name: 'Royal Palace Banquet',
      location: 'Jaipur',
      price: 140000,
      description: 'Grand palace-style banquet venue with luxury decor.',
      image: 'https://images.unsplash.com/photo-1503428593586-e225b39bddfe',
      availability: true,
      isApproved: true,
      createdAt: '2025-02-25T10:00:00Z',
      capacity: 380,
      amenities: ['Luxury Stay', 'Catering', 'WiFi'],
    },
  ];

  saveVenues(sampleVenues);

  // Create sample bookings
  const sampleBookings: Booking[] = [
    {
      id: 'booking-1',
      customerId: 'customer-1',
      providerId: 'provider-1',
      venueId: 'venue-1',
      venueName: 'Grand Ballroom',
      date: '2025-03-15',
      timeSlot: '18:00 - 23:00',
      totalPrice: 2500,
      status: 'confirmed',
      paymentStatus: 'paid',
      createdAt: '2025-02-10T10:00:00Z',
    },
    {
      id: 'booking-2',
      customerId: 'customer-2',
      providerId: 'provider-2',
      venueId: 'venue-3',
      venueName: 'Conference Center',
      date: '2025-02-25',
      timeSlot: '09:00 - 17:00',
      totalPrice: 3200,
      status: 'confirmed',
      paymentStatus: 'paid',
      createdAt: '2025-02-08T10:00:00Z',
    },
    {
      id: 'booking-3',
      customerId: 'customer-1',
      providerId: 'provider-1',
      venueId: 'venue-2',
      venueName: 'Rooftop Terrace',
      date: '2025-04-01',
      timeSlot: '19:00 - 01:00',
      totalPrice: 2100,
      status: 'pending',
      paymentStatus: 'pending',
      createdAt: '2025-02-14T10:00:00Z',
    },
  ];

  saveBookings(sampleBookings);
};
