export interface Venue {
  id: string;
  name: string;
  location: string;
  price: number;
  image: string;
  availability: boolean;
  isApproved: boolean;
  capacity: number;
  amenities: string[];
  description: string;
  rating: number;
}

export interface Booking {
  id: string;
  venueId: string;
  venueName: string;
  date: string;
  timeSlot: string;
  price: number;
  status: 'pending' | 'confirmed' | 'cancelled';
}

export interface Message {
  id: string;
  sender: string;
  text: string;
  timestamp: string;
  isOwn: boolean;
}

export const mockVenues: Venue[] = [
  {
    id: '1',
    name: 'The Leela Palace',
    location: 'New Delhi',
    price: 80000,
    image: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3',
    availability: true,
    isApproved: true,
    capacity: 300,
    amenities: ['Parking', 'WiFi', 'Catering'],
    description: 'Luxury venue for weddings and corporate events.',
    rating: 4.9,
  },
  {
    id: '2',
    name: 'Taj Lands End',
    location: 'Mumbai',
    price: 120000,
    image: 'https://images.unsplash.com/photo-1505236858219-8359eb29e329',
    availability: true,
    isApproved: true,
    capacity: 500,
    amenities: ['Parking', 'Valet', 'Catering'],
    description: 'Premium sea-facing banquet venue.',
    rating: 4.8,
  },
  {
    id: '3',
    name: 'ITC Gardenia',
    location: 'Bengaluru',
    price: 60000,
    image: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3',
    availability: true,
    isApproved: true,
    capacity: 250,
    amenities: ['Garden', 'Outdoor', 'WiFi'],
    description: 'Elegant garden venue for events.',
    rating: 4.7,
  },
  {
    id: '4',
    name: 'Novotel Convention Center',
    location: 'Hyderabad',
    price: 70000,
    image: 'https://images.unsplash.com/photo-1503428593586-e225b39bddfe',
    availability: true,
    isApproved: true,
    capacity: 600,
    amenities: ['WiFi', 'Parking', 'AC'],
    description: 'Modern convention venue.',
    rating: 4.6,
  },
  {
    id: '5',
    name: 'ITC Grand Chola',
    location: 'Chennai',
    price: 90000,
    image: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622',
    availability: true,
    isApproved: true,
    capacity: 400,
    amenities: ['WiFi', 'Catering', 'Parking'],
    description: 'Grand ballroom for large events.',
    rating: 4.8,
  },
  {
    id: '6',
    name: 'JW Marriott',
    location: 'Kolkata',
    price: 85000,
    image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30',
    availability: true,
    isApproved: true,
    capacity: 350,
    amenities: ['WiFi', 'Valet', 'Parking'],
    description: 'Luxury indoor banquet hall.',
    rating: 4.7,
  },
  {
    id: '7',
    name: 'Courtyard by Marriott',
    location: 'Ahmedabad',
    price: 50000,
    image: 'https://images.unsplash.com/photo-1528605248644-14dd04022da1',
    availability: true,
    isApproved: true,
    capacity: 200,
    amenities: ['WiFi', 'Parking', 'Catering'],
    description: 'Perfect venue for mid-size events.',
    rating: 4.6,
  },
  {
    id: '8',
    name: 'Hyatt Pune',
    location: 'Pune',
    price: 60000,
    image: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205',
    availability: true,
    isApproved: true,
    capacity: 300,
    amenities: ['Parking', 'WiFi', 'AC'],
    description: 'Modern banquet for weddings.',
    rating: 4.7,
  },
  {
    id: '9',
    name: 'Radisson Blu',
    location: 'Jaipur',
    price: 55000,
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836',
    available: true,
    capacity: 300,
    amenities: ['Outdoor', 'Parking', 'Catering'],
    description: 'Elegant venue for celebrations.',
    rating: 4.5,
  },
  {
    id: '10',
    name: 'Marriott Hotel',
    location: 'Surat',
    price: 45000,
    image: 'https://images.unsplash.com/photo-1505691938895-1758d7feb511',
    available: true,
    capacity: 250,
    amenities: ['WiFi', 'Parking', 'AC'],
    description: 'Spacious indoor venue.',
    rating: 4.4,
  },
  {
    id: '11',
    name: 'Clarks Avadh',
    location: 'Lucknow',
    price: 50000,
    image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb',
    available: true,
    capacity: 300,
    amenities: ['Parking', 'Catering', 'WiFi'],
    description: 'Classic banquet hall for weddings.',
    rating: 4.5,
  },
  {
    id: '12',
    name: 'The Landmark Hotel',
    location: 'Kanpur',
    price: 40000,
    image: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae',
    available: true,
    capacity: 200,
    amenities: ['WiFi', 'Parking'],
    description: 'Popular venue for events.',
    rating: 4.3,
  },
  {
    id: '13',
    name: 'Radisson Blu',
    location: 'Nagpur',
    price: 45000,
    image: 'https://images.unsplash.com/photo-1478145046317-39f10e56b5e9',
    available: true,
    capacity: 300,
    amenities: ['Parking', 'WiFi'],
    description: 'Modern banquet facility.',
    rating: 4.4,
  },
  {
    id: '14',
    name: 'Sayaji Hotel',
    location: 'Indore',
    price: 55000,
    image: 'https://images.unsplash.com/photo-1492724441997-5dc865305da7',
    available: true,
    capacity: 350,
    amenities: ['WiFi', 'Parking'],
    description: 'Premium venue for functions.',
    rating: 4.6,
  },
  {
    id: '15',
    name: 'Jehan Numa Palace',
    location: 'Bhopal',
    price: 50000,
    image: 'https://images.unsplash.com/photo-1496412705862-e0088f16f791',
    available: true,
    capacity: 200,
    amenities: ['Outdoor', 'Catering'],
    description: 'Royal heritage venue.',
    rating: 4.6,
  },
  {
    id: '16',
    name: 'Hotel Maurya',
    location: 'Patna',
    price: 45000,
    image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858',
    available: true,
    capacity: 250,
    amenities: ['Parking', 'WiFi'],
    description: 'Well-known banquet venue.',
    rating: 4.4,
  },
  {
    id: '17',
    name: 'Capitol Hill',
    location: 'Ranchi',
    price: 35000,
    image: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187',
    available: true,
    capacity: 200,
    amenities: ['WiFi', 'Parking'],
    description: 'Comfortable venue for events.',
    rating: 4.2,
  },
  {
    id: '18',
    name: 'Hotel Babylon',
    location: 'Raipur',
    price: 40000,
    image: 'https://images.unsplash.com/photo-1499951360447-b19be8fe80f5',
    available: true,
    capacity: 250,
    amenities: ['WiFi', 'Parking'],
    description: 'Modern banquet space.',
    rating: 4.3,
  },
  {
    id: '19',
    name: 'Taj Chandigarh',
    location: 'Chandigarh',
    price: 70000,
    image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85',
    available: true,
    capacity: 300,
    amenities: ['Valet', 'WiFi'],
    description: 'Luxury venue with premium services.',
    rating: 4.8,
  },
  {
    id: '20',
    name: 'Hyatt Regency',
    location: 'Amritsar',
    price: 60000,
    image: 'https://images.unsplash.com/photo-1505691723518-36a5ac3b2e1b',
    available: true,
    capacity: 250,
    amenities: ['WiFi', 'Parking'],
    description: 'Stylish event venue.',
    rating: 4.7,
  },
  {
    id: '21',
    name: 'Radisson Blu',
    location: 'Ludhiana',
    price: 50000,
    image: 'https://images.unsplash.com/photo-1505691938895-1758d7feb511',
    available: true,
    capacity: 250,
    amenities: ['Parking', 'WiFi'],
    description: 'Elegant banquet hall.',
    rating: 4.5,
  },
  {
    id: '22',
    name: 'Hotel Clarks Shiraz',
    location: 'Agra',
    price: 55000,
    image: 'https://images.unsplash.com/photo-1494526585095-c41746248156',
    available: true,
    capacity: 300,
    amenities: ['Catering', 'Parking'],
    description: 'Venue near Taj Mahal.',
    rating: 4.6,
  },
  {
    id: '23',
    name: 'Taj Ganges',
    location: 'Varanasi',
    price: 50000,
    image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85',
    available: true,
    capacity: 200,
    amenities: ['WiFi', 'Parking'],
    description: 'Peaceful venue with heritage feel.',
    rating: 4.5,
  },
  {
    id: '24',
    name: 'Hotel Harmony Inn',
    location: 'Meerut',
    price: 30000,
    image: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae',
    available: true,
    capacity: 150,
    amenities: ['Parking'],
    description: 'Affordable event venue.',
    rating: 4.1,
  },
  {
    id: '25',
    name: 'Le Meridien',
    location: 'Coimbatore',
    price: 50000,
    image: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb',
    available: true,
    capacity: 250,
    amenities: ['WiFi', 'Parking'],
    description: 'Modern banquet hall.',
    rating: 4.4,
  },
  {
    id: '26',
    name: 'Heritage Madurai',
    location: 'Madurai',
    price: 45000,
    image: 'https://images.unsplash.com/photo-1484154218962-a197022b5858',
    available: true,
    capacity: 200,
    amenities: ['Garden', 'Parking'],
    description: 'Luxury outdoor venue.',
    rating: 4.5,
  },
  {
    id: '27',
    name: 'Novotel',
    location: 'Visakhapatnam',
    price: 60000,
    image: 'https://images.unsplash.com/photo-1470337458703-46ad1756a187',
    available: true,
    capacity: 300,
    amenities: ['WiFi', 'Parking'],
    description: 'Sea-facing banquet venue.',
    rating: 4.6,
  },
  {
    id: '28',
    name: 'The Gateway Hotel',
    location: 'Vijayawada',
    price: 45000,
    image: 'https://images.unsplash.com/photo-1499951360447-b19be8fe80f5',
    available: true,
    capacity: 250,
    amenities: ['WiFi', 'Parking'],
    description: 'Comfortable venue for events.',
    rating: 4.3,
  },
  {
    id: '29',
    name: 'Hyatt Regency',
    location: 'Thiruvananthapuram',
    price: 60000,
    image: 'https://images.unsplash.com/photo-1505691723518-36a5ac3b2e1b',
    available: true,
    capacity: 250,
    amenities: ['WiFi', 'Parking'],
    description: 'Premium indoor venue.',
    rating: 4.6,
  },
  {
    id: '30',
    name: 'Grand Hyatt',
    location: 'Kochi',
    price: 90000,
    image: 'https://images.unsplash.com/photo-1494526585095-c41746248156',
    available: true,
    capacity: 400,
    amenities: ['Parking', 'WiFi'],
    description: 'Luxury waterfront venue.',
    rating: 4.8,
  },
  {
    id: '31',
    name: 'Radisson Blu',
    location: 'Mysuru',
    price: 50000,
    image: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622',
    available: true,
    capacity: 200,
    amenities: ['WiFi', 'Parking'],
    description: 'Elegant venue for events.',
    rating: 4.5,
  },
  {
    id: '32',
    name: 'Goldfinch Hotel',
    location: 'Mangaluru',
    price: 40000,
    image: 'https://images.unsplash.com/photo-1505236858219-8359eb29e329',
    available: true,
    capacity: 200,
    amenities: ['Parking', 'WiFi'],
    description: 'Modern banquet venue.',
    rating: 4.4,
  },
  {
    id: '33',
    name: 'Umaid Bhawan Palace',
    location: 'Jodhpur',
    price: 200000,
    image: 'https://images.unsplash.com/photo-1503428593586-e225b39bddfe',
    available: true,
    capacity: 300,
    amenities: ['Luxury Stay', 'Catering'],
    description: 'Royal palace wedding venue.',
    rating: 4.9,
  },
  {
    id: '34',
    name: 'The Oberoi Udaivilas',
    location: 'Udaipur',
    price: 180000,
    image: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3',
    available: true,
    capacity: 200,
    amenities: ['Lake View', 'Luxury'],
    description: 'Luxury lake-side wedding venue.',
    rating: 4.9,
  },
  {
    id: '35',
    name: 'Hyatt Regency',
    location: 'Dehradun',
    price: 50000,
    image: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae',
    available: true,
    capacity: 200,
    amenities: ['Parking', 'WiFi'],
    description: 'Peaceful hill venue.',
    rating: 4.5,
  },
  {
    id: '36',
    name: 'Crystal Banquet Hall',
    location: 'Gurgaon',
    price: 65000,
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750',
    available: true,
    capacity: 280,
    amenities: ['WiFi', 'Catering', 'Parking'],
    description: 'Elegant hall with modern lighting and stage facilities.',
    rating: 4.6,
  },
  {
    id: '37',
    name: 'Island View Lounge',
    location: 'Goa',
    price: 95000,
    image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85',
    available: true,
    capacity: 220,
    amenities: ['Outdoor', 'Bar', 'Parking'],
    description: 'Seaside lounge venue with panoramic views and premium service.',
    rating: 4.7,
  },
  {
    id: '38',
    name: 'Emerald Conference Hall',
    location: 'Chandigarh',
    price: 52000,
    image: 'https://images.unsplash.com/photo-1494526585095-c41746248156',
    available: true,
    capacity: 260,
    amenities: ['WiFi', 'Projector', 'Parking'],
    description: 'Business-friendly conference hall with full AV support.',
    rating: 4.4,
  },
  {
    id: '39',
    name: 'Lotus Garden Estate',
    location: 'Noida',
    price: 78000,
    image: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205',
    available: true,
    capacity: 420,
    amenities: ['Outdoor', 'Catering', 'Parking'],
    description: 'Lush garden estate perfect for large outdoor weddings.',
    rating: 4.8,
  },
  {
    id: '40',
    name: 'Royal Palace Banquet',
    location: 'Jaipur',
    price: 140000,
    image: 'https://images.unsplash.com/photo-1503428593586-e225b39bddfe',
    available: true,
    capacity: 380,
    amenities: ['Luxury Stay', 'Catering', 'WiFi'],
    description: 'Grand palace-style banquet venue with luxury decor.',
    rating: 4.9,
  },
];

export const timeSlots = [
  '9:00 AM - 12:00 PM',
  '12:00 PM - 3:00 PM',
  '3:00 PM - 6:00 PM',
  '6:00 PM - 9:00 PM',
  '9:00 PM - 12:00 AM',
];

export const locations = [
  'All Locations',
  'Mumbai',
  'Delhi',
  'Bengaluru',
  'Hyderabad',
  'Chennai',
  'Kolkata',
  'Ahmedabad',
  'Pune',
  'Jaipur',
  'Surat',
  'Lucknow',
  'Kanpur',
  'Nagpur',
  'Indore',
  'Bhopal',
  'Patna',
  'Ranchi',
  'Raipur',
  'Chandigarh',
  'Amritsar',
  'Ludhiana',
  'Agra',
  'Varanasi',
  'Meerut',
  'Coimbatore',
  'Madurai',
  'Visakhapatnam',
  'Vijayawada',
  'Thiruvananthapuram',
  'Kochi',
  'Mysuru',
  'Mangaluru',
  'Jodhpur',
  'Udaipur',
  'Dehradun',
];

// Storage utilities
export const getVenues = (): Venue[] => {
  const stored = localStorage.getItem('venuebooking_venues');
  return stored ? JSON.parse(stored) : mockVenues;
};

export const saveVenues = (venues: Venue[]) => {
  localStorage.setItem('venuebooking_venues', JSON.stringify(venues));
};

export const getBookings = (): Booking[] => {
  const stored = localStorage.getItem('venuebooking_bookings');
  return stored ? JSON.parse(stored) : [];
};

export const saveBooking = (booking: Booking) => {
  const bookings = getBookings();
  bookings.push(booking);
  localStorage.setItem('venuebooking_bookings', JSON.stringify(bookings));
};

export const getMessages = (): Message[] => {
  const stored = localStorage.getItem('venuebooking_messages');
  return stored ? JSON.parse(stored) : [];
};

export const saveMessage = (message: Message) => {
  const messages = getMessages();
  messages.push(message);
  localStorage.setItem('venuebooking_messages', JSON.stringify(messages));
};

// Initialize venues if not already in storage
if (!localStorage.getItem('venuebooking_venues')) {
  saveVenues(mockVenues);
}